# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b77c8af779ba453a77b2c8efa40f63f267d3e8926a11488efb911314da9ce5355acc09d99b54563f994e7603d96e9c6058ee51224a9b85e631946dd2972fac8a

test:
  secret_key_base: c7dc1cf372547d4524ab2709dd25f6d1625402084003f08e4a74a4583e6337138dbd15ccb894161571786449cab389bdf15d1265c22d0cc1b663d899d6294107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
